const KEY='school-timetable-v01';
const stageDefaults=[['الأول',1,'#587B9B'],['الثاني',2,'#6F8F72'],['الثالث',3,'#9A7B60'],['الرابع',4,'#7D7398'],['الخامس',5,'#A16F78'],['السادس',6,'#557F83']];
const defaultDays=[['الأحد',7,true],['الاثنين',7,true],['الثلاثاء',6,true],['الأربعاء',7,true],['الخميس',5,true],['الجمعة',0,false],['السبت',0,false]];
let db=load(); let page='school';
function seed(){return {school:{name:'',year:'2026-2027'},days:defaultDays.map((x,i)=>({id:'d'+i,name:x[0],periods:x[1],active:x[2],order:i+1})),stages:stageDefaults.map(x=>({id:'g'+x[1],name:x[0],order:x[1],color:x[2]})),sections:[],subjects:[],teachers:[],assignments:[]}}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||seed()}catch{return seed()}}
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderSummary()}
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>p+'_'+Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const pages=[['school','1. المدرسة'],['days','2. الأيام والحصص'],['sections','3. المراحل والشعب'],['subjects','4. المواد'],['teachers','5. المدرسون'],['assignments','6. التكليفات']];
function nav(){ $('#steps').innerHTML=pages.map(x=>`<button class='step ${page===x[0]?'active':''}' data-p='${x[0]}'>${x[1]}</button>`).join(''); document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{page=b.dataset.p;render()}) }
function completeness(){let checks=[!!db.school.name,db.days.some(d=>d.active&&d.periods>0),db.sections.length>0,db.subjects.length>0,db.teachers.length>0,db.assignments.length>0];return Math.round(checks.filter(Boolean).length/checks.length*100)}
function renderSummary(){let s=$('#summary'); if(!s)return;s.innerHTML=`<div class='cards'><div class='stat'>اكتمال البيانات<b>${completeness()}%</b></div><div class='stat'>الشعب<b>${db.sections.length}</b></div><div class='stat'>المواد<b>${db.subjects.length}</b></div><div class='stat'>المدرسون<b>${db.teachers.length}</b></div><div class='stat'>التكليفات<b>${db.assignments.length}</b></div></div><div class='progress' style='margin-top:12px'><i style='width:${completeness()}%'></i></div>`}
function render(){nav();renderSummary();({school,days,sections,subjects,teachers,assignments}[page])()}
function school(){ $('#workspace').innerHTML=`<h2>إعداد المدرسة</h2><div class='grid'><div class='field'><label>اسم المدرسة</label><input id='schoolName' value='${esc(db.school.name)}'></div><div class='field'><label>العام الدراسي</label><input id='schoolYear' value='${esc(db.school.year)}'></div></div><div class='actions'><button id='saveSchool'>حفظ الإعدادات</button><button class='secondary' id='importBtn'>استيراد نسخة احتياطية</button><button class='danger' id='resetBtn'>إعادة ضبط المشروع</button></div>`; $('#saveSchool').onclick=()=>{db.school.name=$('#schoolName').value.trim();db.school.year=$('#schoolYear').value.trim();save()};$('#importBtn').onclick=()=>$('#importFile').click();$('#resetBtn').onclick=()=>{if(confirm('سيتم حذف جميع البيانات المحلية. هل أنت متأكد؟')){db=seed();save();render()}} }
function days(){ $('#workspace').innerHTML=`<h2>أيام الدوام وعدد الحصص</h2><div class='notice'>يمكن أن يختلف عدد الحصص من يوم إلى آخر.</div><table><thead><tr><th>اليوم</th><th>دوام</th><th>عدد الحصص</th></tr></thead><tbody>${db.days.sort((a,b)=>a.order-b.order).map(d=>`<tr><td>${d.name}</td><td><input type='checkbox' data-active='${d.id}' ${d.active?'checked':''}></td><td><input type='number' min='0' max='12' data-periods='${d.id}' value='${d.periods}'></td></tr>`).join('')}</tbody></table>`;document.querySelectorAll('[data-active]').forEach(x=>x.onchange=()=>{db.days.find(d=>d.id===x.dataset.active).active=x.checked;save()});document.querySelectorAll('[data-periods]').forEach(x=>x.onchange=()=>{let d=db.days.find(d=>d.id===x.dataset.periods);d.periods=Math.max(0,+x.value||0);d.active=d.periods>0;save();render()}) }
function sections(){let rows=db.sections.slice().sort((a,b)=>{let ga=db.stages.find(g=>g.id===a.stageId),gb=db.stages.find(g=>g.id===b.stageId);return ga.order-gb.order||a.order-b.order});$('#workspace').innerHTML=`<h2>المراحل والشعب</h2><div class='grid'><div class='field'><label>المرحلة</label><select id='stage'>${db.stages.sort((a,b)=>a.order-b.order).map(g=>`<option value='${g.id}'>${g.name}</option>`).join('')}</select></div><div class='field'><label>اسم الشعبة</label><input id='sectionName' placeholder='مثال: أ'></div></div><div class='actions'><button id='addSection'>إضافة شعبة</button></div><table><thead><tr><th>المرحلة</th><th>الشعبة</th><th></th></tr></thead><tbody>${rows.length?rows.map(s=>{let g=db.stages.find(x=>x.id===s.stageId);return `<tr><td><span class='stage-dot' style='background:${g.color}'></span>${g.name}</td><td>${esc(s.name)}</td><td><button class='danger' data-del-section='${s.id}'>حذف</button></td></tr>`}).join(''):`<tr><td colspan='3' class='empty'>لم تضف شعب بعد</td></tr>`}</tbody></table>`;$('#addSection').onclick=()=>{let name=$('#sectionName').value.trim();if(!name)return;let stageId=$('#stage').value;if(db.sections.some(s=>s.stageId===stageId&&s.name===name))return alert('هذه الشعبة موجودة');let max=Math.max(0,...db.sections.filter(s=>s.stageId===stageId).map(s=>s.order));db.sections.push({id:uid('sec'),stageId,name,order:max+1});save();sections()};document.querySelectorAll('[data-del-section]').forEach(b=>b.onclick=()=>{if(db.assignments.some(a=>a.sectionId===b.dataset.delSection))return alert('لا يمكن حذف شعبة مرتبطة بتكليف');db.sections=db.sections.filter(s=>s.id!==b.dataset.delSection);save();sections()}) }
function subjects(){ $('#workspace').innerHTML=`<h2>المواد الدراسية</h2><div class='grid'><div class='field'><label>اسم المادة</label><input id='subjectName' placeholder='رياضيات'></div><div class='field'><label>لون هادئ للمادة</label><input id='subjectColor' type='color' value='#DCE8F2'></div></div><div class='actions'><button id='addSubject'>إضافة مادة</button></div>${simpleTable(db.subjects,['الاسم','اللون'],x=>[esc(x.name),`<span class='tag' style='background:${x.color}'>${x.color}</span>`],'subject')}`;$('#addSubject').onclick=()=>{let name=$('#subjectName').value.trim();if(!name)return;if(db.subjects.some(x=>x.name===name))return alert('المادة موجودة');db.subjects.push({id:uid('sub'),name,color:$('#subjectColor').value});save();subjects()};delWire('subject','subjects',subjects,'subjectId') }
function teachers(){ $('#workspace').innerHTML=`<h2>المدرسون</h2><div class='grid'><div class='field'><label>الاسم الكامل</label><input id='teacherName'></div><div class='field'><label>التخصص</label><input id='teacherSpec'></div><div class='field'><label>ملاحظات</label><input id='teacherNotes'></div></div><div class='actions'><button id='addTeacher'>إضافة مدرس</button></div><hr style='border:0;border-top:1px solid var(--line);margin:20px 0'><h3>إدخال جماعي</h3><div class='notice'>الصق كل مدرس في سطر. يمكن فصل: الاسم، التخصص، الملاحظات بواسطة Tab أو فاصلة.</div><div class='field'><textarea id='bulkTeachers' placeholder='أحمد سعدون\tرياضيات\nمحمد علي\tفيزياء'></textarea></div><div class='actions'><button id='bulkAdd'>معاينة وإضافة</button></div>${simpleTable(db.teachers,['الاسم','التخصص','ملاحظات'],x=>[esc(x.name),esc(x.specialty),esc(x.notes)],'teacher')}`;function add(name,specialty='',notes=''){name=name.trim();if(!name||db.teachers.some(t=>t.name===name))return false;db.teachers.push({id:uid('tea'),name,specialty:specialty.trim(),notes:notes.trim()});return true}$('#addTeacher').onclick=()=>{if(add($('#teacherName').value,$('#teacherSpec').value,$('#teacherNotes').value)){save();teachers()}else alert('الاسم فارغ أو مكرر')};$('#bulkAdd').onclick=()=>{let lines=$('#bulkTeachers').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),added=0,dups=[];lines.forEach(line=>{let p=line.includes('\t')?line.split('\t'):line.split(',');if(add(p[0]||'',p[1]||'',p.slice(2).join(' ')))added++;else dups.push(p[0])});save();alert(`تمت إضافة ${added} مدرس. ${dups.length?'المكرر/غير الصالح: '+dups.join('، '):''}`);teachers()};delWire('teacher','teachers',teachers,'teacherId') }
function assignments(){let optsSec=db.sections.slice().sort((a,b)=>{let ga=db.stages.find(g=>g.id===a.stageId),gb=db.stages.find(g=>g.id===b.stageId);return ga.order-gb.order||a.order-b.order});$('#workspace').innerHTML=`<h2>تكليفات المدرسين</h2>${(!db.teachers.length||!db.subjects.length||!db.sections.length)?`<div class='notice error'>يجب إضافة مدرس واحد ومادة واحدة وشعبة واحدة على الأقل.</div>`:''}<div class='grid'><div class='field'><label>المدرس</label><select id='aTeacher'>${db.teachers.map(x=>`<option value='${x.id}'>${esc(x.name)}</option>`).join('')}</select></div><div class='field'><label>المادة</label><select id='aSubject'>${db.subjects.map(x=>`<option value='${x.id}'>${esc(x.name)}</option>`).join('')}</select></div><div class='field'><label>الشعبة</label><select id='aSection'>${optsSec.map(s=>{let g=db.stages.find(x=>x.id===s.stageId);return `<option value='${s.id}'>${g.name} ${esc(s.name)}</option>`}).join('')}</select></div><div class='field'><label>الحصص الأسبوعية</label><input id='aWeekly' type='number' min='1' max='20' value='4'></div></div><div class='actions'><button id='addAssignment'>إضافة تكليف</button></div><table><thead><tr><th>المدرس</th><th>المادة</th><th>الشعبة</th><th>الحصص/أسبوع</th><th></th></tr></thead><tbody>${db.assignments.length?db.assignments.map(a=>{let t=db.teachers.find(x=>x.id===a.teacherId),su=db.subjects.find(x=>x.id===a.subjectId),se=db.sections.find(x=>x.id===a.sectionId),g=se&&db.stages.find(x=>x.id===se.stageId);return `<tr><td>${esc(t?.name||'—')}</td><td>${esc(su?.name||'—')}</td><td>${g?g.name+' '+esc(se.name):'—'}</td><td>${a.weeklyPeriods}</td><td><button class='danger' data-del-a='${a.id}'>حذف</button></td></tr>`}).join(''):`<tr><td colspan='5' class='empty'>لا توجد تكليفات</td></tr>`}</tbody></table>`;$('#addAssignment').onclick=()=>{let teacherId=$('#aTeacher').value,subjectId=$('#aSubject').value,sectionId=$('#aSection').value,weeklyPeriods=+$('#aWeekly').value;if(!teacherId||!subjectId||!sectionId||weeklyPeriods<1)return alert('أكمل البيانات');if(db.assignments.some(a=>a.teacherId===teacherId&&a.subjectId===subjectId&&a.sectionId===sectionId))return alert('هذا التكليف موجود مسبقاً');db.assignments.push({id:uid('asg'),teacherId,subjectId,sectionId,weeklyPeriods});save();assignments()};document.querySelectorAll('[data-del-a]').forEach(b=>b.onclick=()=>{db.assignments=db.assignments.filter(a=>a.id!==b.dataset.delA);save();assignments()}) }
function simpleTable(arr,heads,row,type){return `<table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}<th></th></tr></thead><tbody>${arr.length?arr.map(x=>`<tr>${row(x).map(c=>`<td>${c}</td>`).join('')}<td><button class='danger' data-del-${type}='${x.id}'>حذف</button></td></tr>`).join(''):`<tr><td colspan='${heads.length+1}' class='empty'>لا توجد بيانات</td></tr>`}</tbody></table>`}
function delWire(type,collection,rerender,ref){document.querySelectorAll(`[data-del-${type}]`).forEach(b=>b.onclick=()=>{let id=b.dataset['del'+type[0].toUpperCase()+type.slice(1)];if(db.assignments.some(a=>a[ref]===id))return alert('لا يمكن الحذف لأنه مرتبط بتكليف');db[collection]=db[collection].filter(x=>x.id!==id);save();rerender()})}
$('#exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='school-timetable-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('#importFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();render();alert('تم الاستيراد بنجاح')}catch{alert('ملف غير صالح')}};r.readAsText(f)};
render();
